# Generated by Django 3.1.3 on 2021-01-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fallowEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.CharField(max_length=50, verbose_name='Takip eden')),
                ('followed', models.CharField(max_length=50, verbose_name='Takip edilen')),
            ],
        ),
    ]
