# Generated by Django 3.1.3 on 2021-01-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fallowEvent',
        ),
    ]
